# Generated by Django 4.1.2 on 2022-10-10 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_dept', models.CharField(choices=[('1', 'IT'), ('2', 'Accounts'), ('3', 'HR'), ('4', 'Procurement')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intial', models.Field(unique=True)),
                ('status', models.CharField(choices=[('1', 'active'), ('2', 'inactive')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=100)),
                ('emp_salary', models.FloatField()),
                ('date_join', models.DateField()),
                ('emp_address', models.TextField()),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.dept')),
            ],
        ),
    ]
